name: Tests

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install depfinder
        run: >
          python -m pip install -e .
          && pip install -r requirements-dev.txt

      - name: test w/o conda-forge-metadata
        run: >
          depfinder --help
          && python -m pip install -e . --force-reinstall
          && coverage run -m pytest -vrsx test.py

      - name: test w/ conda-forge-metadata
        if: matrix.python-version != '3.9'
        run: >
          python -m pip install -e .[conda-forge] --force-reinstall
          && coverage run -m pytest -vrsx test.py

      - name: coverage
        run: >
          coverage report -m
          && codecov

