name: Tests

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install depfinder
        run: >
          python -m pip install -e .
          && pip install -r requirements-dev.txt

      - name: test w/o conda-forge-metadata
        run: >
          depfinder --help
          && python -m pip install -e . --force-reinstall
          && coverage run -m pytest -vrsx test.py

      - name: test w/ conda-forge-metadata
        run: >
          python -m pip install -e .[conda-forge] --force-reinstall
          && coverage run -m pytest -vrsx test.py

      - name: coverage
        run: >
          coverage report -m
          && codecov

